package attrvalue

import (
	"fmt"
	"reflect"
	"slices"

	"github.com/terraform-linters/tflint-plugin-sdk/hclext"
	"github.com/terraform-linters/tflint-plugin-sdk/tflint"
)

// SimpleRule checks whether a string attribute value is one of the expected values.
// It can be used to check string, number, and bool attributes.
type SimpleRule[T any] struct {
	tflint.DefaultRule // Embed the default rule to reuse its implementation

	resourceType    string  // e.g. "azurerm_storage_account"
	nestedBlockType *string // e.g. "sku"
	attributeName   string  // e.g. "account_replication_type"
	expectedValues  []T     // e.g. []string{"ZRS"}
}

var _ tflint.Rule = (*SimpleRule[any])(nil)

// NewSimpleRule returns a new rule with the given resource type, attribute name, and expected values.
func NewSimpleRule[T any](resourceType, attributeName string, expectedValues []T) *SimpleRule[T] {
	return &SimpleRule[T]{
		resourceType:   resourceType,
		attributeName:  attributeName,
		expectedValues: expectedValues,
	}
}

// NewSimpleRule returns a new rule with the given resource type, attribute name, and expected values.
func NewSimpleNestedBlockRule[T any](resourceType, nestedBlockType, attributeName string, expectedValues []T) *SimpleRule[T] {
	return &SimpleRule[T]{
		resourceType:    resourceType,
		attributeName:   attributeName,
		nestedBlockType: &nestedBlockType,
		expectedValues:  expectedValues,
	}
}

func (r *SimpleRule[T]) Name() string {
	return fmt.Sprintf("%s.%s must be: %+v", r.resourceType, r.attributeName, r.expectedValues)
}

func (r *SimpleRule[T]) Enabled() bool {
	return true
}

func (r *SimpleRule[T]) Severity() tflint.Severity {
	return tflint.ERROR
}

func (r *SimpleRule[T]) Check(runner tflint.Runner) error {
	var attrs []*hclext.Attribute
	var err error
	if r.nestedBlockType == nil {
		attrs, err = getSimpleAttrs(runner, r.resourceType, r.attributeName)
	} else {
		attrs, err = getNestedBlockAttrs(runner, r.resourceType, *r.nestedBlockType, r.attributeName)
	}
	if err != nil {
		return err
	}

	for _, attr := range attrs {
		var dt T
		val := toPtr(dt)
		ctyType, err := toCtyType(dt)
		if err != nil {
			return err
		}
		if err = runner.EvaluateExpr(attr.Expr, val, &tflint.EvaluateExprOption{
			WantType: &ctyType,
		}); err != nil {
			if slices.Contains([]string{
				"null value found",           // generated by tflint.
				"null value is not allowed"}, // generated by the test runner.
				err.Error()) {
				continue
			}
			return err
		}
		found := false
		for _, expected := range r.expectedValues {
			exp := toPtr(expected)
			if reflect.DeepEqual(val, exp) {
				found = true
				break
			}
		}
		if !found {
			v := reflect.Indirect(reflect.ValueOf(val))
			return runner.EmitIssue(
				r,
				fmt.Sprintf("%v is an invalid attribute value of `%s` - expecting (one of) %v", v, r.attributeName, r.expectedValues),
				attr.Range,
			)
		}
	}
	return nil
}
