$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$readmePath = Join-Path $root 'README.md'
$rulesPath = Join-Path $root 'RULES.md'
$startMarker = '<!-- RULES:START -->'
$endMarker = '<!-- RULES:END -->'

Push-Location $root
try {
    go generate ./...
    if ($LASTEXITCODE -ne 0) {
        throw 'go generate failed'
    }
}
finally {
    Pop-Location
}

$rulesLines = [IO.File]::ReadAllText($rulesPath) -split '\r?\n'
$tableStart = [Array]::FindIndex(
    $rulesLines,
    [Predicate[string]] { param($line) $line.StartsWith('| Name') }
)
if ($tableStart -lt 0) {
    throw 'Could not find the rules table in RULES.md'
}

$tableEnd = $tableStart
while ($tableEnd -lt $rulesLines.Count -and $rulesLines[$tableEnd].StartsWith('|')) {
    $tableEnd++
}
$table = $rulesLines[$tableStart..($tableEnd - 1)] -join "`n"

$readme = [IO.File]::ReadAllText($readmePath)
$sectionStart = $readme.IndexOf($startMarker, [StringComparison]::Ordinal)
$sectionEnd = $readme.IndexOf($endMarker, $sectionStart, [StringComparison]::Ordinal)
if ($sectionStart -lt 0 -or $sectionEnd -lt 0) {
    throw 'Could not find the rules markers in README.md'
}
$sectionEnd += $endMarker.Length

$generatedSection = @"
$startMarker
<!-- This section is auto-generated by scripts/Update-Readme.ps1. Do not edit manually. -->

$table
$endMarker
"@
$generatedSection = $generatedSection.TrimEnd("`r", "`n")

$updated = $readme.Substring(0, $sectionStart) + $generatedSection + $readme.Substring($sectionEnd)
[IO.File]::WriteAllText($readmePath, $updated, [Text.UTF8Encoding]::new($false))
