#!/usr/bin/env bash
# Regenerate RULES.md from the registered rules and splice the resulting
# table into README.md between the <!-- RULES:START --> / <!-- RULES:END -->
# markers.
#
# Intended to be run locally (`./scripts/update-readme.sh`) or from CI via
# .github/workflows/update-readme.yml.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
README="$ROOT/README.md"
RULES="$ROOT/RULES.md"
START_MARKER="<!-- RULES:START -->"
END_MARKER="<!-- RULES:END -->"

cd "$ROOT"

echo "==> Regenerating RULES.md via 'go generate ./...'"
go generate ./...

[[ -f "$README" ]] || { echo "README.md not found at $README" >&2; exit 1; }
[[ -f "$RULES"  ]] || { echo "RULES.md not found at $RULES (did 'go generate' fail?)" >&2; exit 1; }
grep -qF "$START_MARKER" "$README" || { echo "Start marker missing in README.md" >&2; exit 1; }
grep -qF "$END_MARKER"   "$README" || { echo "End marker missing in README.md" >&2; exit 1; }

echo "==> Splicing RULES.md table into README.md"
README_PATH="$README" \
RULES_PATH="$RULES" \
START="$START_MARKER" \
END="$END_MARKER" \
python3 <<'PY'
import os, re

readme_path = os.environ["README_PATH"]
rules_path  = os.environ["RULES_PATH"]
start       = os.environ["START"]
end         = os.environ["END"]

with open(rules_path, "r", encoding="utf-8") as f:
    rules = f.read()

# Extract the markdown table (first header row through the last table row).
# The rulesdoc generator writes a single table; grab from the first '|' header
# line to the end of the contiguous table block.
lines = rules.splitlines()
try:
    start_idx = next(i for i, line in enumerate(lines) if line.startswith("| Name"))
except StopIteration:
    raise SystemExit("Could not find rules table in RULES.md")

end_idx = start_idx
while end_idx < len(lines) and lines[end_idx].startswith("|"):
    end_idx += 1

table = "\n".join(lines[start_idx:end_idx]).rstrip()

new_section = (
    f"{start}\n"
    "<!-- This section is auto-generated by scripts/update-readme.sh. Do not edit manually. -->\n"
    "\n"
    f"{table}\n"
    f"{end}"
)

with open(readme_path, "r", encoding="utf-8") as f:
    content = f.read()

pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
if not pattern.search(content):
    raise SystemExit("Markers not found in README.md")

updated = pattern.sub(lambda _: new_section, content, count=1)

if updated == content:
    print("README.md already up to date.")
else:
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(updated)
    print("README.md updated.")
PY
