---
name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    name: ${{ matrix.os }} (${{ matrix.version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [v0.50.3, latest]
    env:
      TFLINT_VERSION: ${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version-file: 'go.mod'

    - name: Install TFLint
      # v0.56.0
      run: curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/f95d8c83c7656cc2dbbc035c11bf87ac0485b070/install_linux.sh | bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install plugin (Linux)
      if: runner.os == 'Linux'
      run: make install

    - name: Install plugin (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir -p ~/.tflint.d/plugins
        go build -o ~/.tflint.d/plugins/tflint-ruleset-avm.exe
      shell: bash

    - name: Run E2E tests
      run: make e2e
