---
name: Lint Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - 'vendor/**'
      - '.github/workflows/**'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd #v7.0.0
        with:
          version: v2.0

      - name: Run Gosec Security Scanner
        uses: securego/gosec@955a68d0d19f4afb7503068f95059f7d0c529017 # v2.22.3
        env:
          GOFLAGS: "-buildvcs=false"
        with:
          args: './...'
